logging:
    level:
        org:
            atmosphere: warn
server:
    port: ${PORT:8080}
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: ''
        url: jdbc:postgresql://localhost:5432/rejects
        username: tjm
vaadin:
    compatibilityMode: false
    whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,com.example.application
